### ISSUE TITLE
Pip installation problems M1 macOS

### ISSUE THREAD

**Issue by steinjohannes** [jungmannlab/picasso#258]
* Picasso version: 76a1ead4c224090f80a6af1662a122998e9dfe99
* Python version: 3.8
* Operating System: M1 macOS Monterey

### Description

Following the pip installation guide and after apparent succesful installation, I receive the following error code when calling a picasso module (e.g. localize): ModuleNotFoundError: No module named 'picasso.ext'

### What I Did

- conda create —name picasso_sr python=3.8
- conda activate picasso_sr
- conda install -c anaconda pyqt 
- pip install picassosr
- picasso localize

```
(base) wyssuser@wyss12422 ~ % conda create --name picasso_sr python=3.8 
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/wyssuser/opt/anaconda3/envs/picasso_sr

  added / updated specs:
    - python=3.8


The following NEW packages will be INSTALLED:

  ca-certificates    pkgs/main/osx-64::ca-certificates-2022.4.26-hecd8cb5_0
  certifi            pkgs/main/osx-64::certifi-2022.6.15-py38hecd8cb5_0
  libcxx             pkgs/main/osx-64::libcxx-12.0.0-h2f01273_0
  libffi             pkgs/main/osx-64::libffi-3.3-hb1e8313_2
  ncurses            pkgs/main/osx-64::ncurses-6.3-hca72f7f_3
  openssl            pkgs/main/osx-64::openssl-1.1.1q-hca72f7f_0
  pip                pkgs/main/osx-64::pip-22.1.2-py38hecd8cb5_0
  python             pkgs/main/osx-64::python-3.8.13-hdfd78df_0
  readline           pkgs/main/osx-64::readline-8.1.2-hca72f7f_1
  setuptools         pkgs/main/osx-64::setuptools-61.2.0-py38hecd8cb5_0
  sqlite             pkgs/main/osx-64::sqlite-3.38.5-h707629a_0
  tk                 pkgs/main/osx-64::tk-8.6.12-h5d9f67b_0
  wheel              pkgs/main/noarch::wheel-0.37.1-pyhd3eb1b0_0
  xz                 pkgs/main/osx-64::xz-5.2.5-hca72f7f_1
  zlib               pkgs/main/osx-64::zlib-1.2.12-h4dc903c_2


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate picasso_sr
#
# To deactivate an active environment, use
#
#     $ conda deactivate



(base) wyssuser@wyss12422 ~ % conda activate picasso_sr
(picasso_sr) wyssuser@wyss12422 ~ % conda install -c anaconda pyqt
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/wyssuser/opt/anaconda3/envs/picasso_sr

  added / updated specs:
    - pyqt


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2022.4.26  |       hecd8cb5_0         132 KB  anaconda
    certifi-2022.6.15          |   py38hecd8cb5_0         157 KB  anaconda
    dbus-1.13.18               |       h18a8e69_0         550 KB  anaconda
    expat-2.4.4                |       he9d5cce_0         145 KB  anaconda
    gettext-0.21.0             |       h7535e17_0         3.4 MB  anaconda
    glib-2.69.1                |       h8346a28_1         3.3 MB  anaconda
    icu-58.2                   |       h0a44026_3        22.6 MB  anaconda
    jpeg-9e                    |       hca72f7f_0         266 KB  anaconda
    libiconv-1.16              |       hca72f7f_2         1.3 MB  anaconda
    libpng-1.6.37              |       ha441bb4_0         325 KB  anaconda
    libxml2-2.9.14             |       hbf8cd5e_0         686 KB  anaconda
    llvm-openmp-12.0.0         |       h0dcd299_1         300 KB  anaconda
    openssl-1.1.1o             |       hca72f7f_0         3.5 MB  anaconda
    pcre-8.45                  |       h23ab428_0         221 KB  anaconda
    pyqt-5.9.2                 |   py38h655552a_2         4.4 MB  anaconda
    qt-5.9.7                   |       h468cd18_1        76.8 MB  anaconda
    sip-4.19.8                 |   py38h0a44026_0         253 KB  anaconda
    ------------------------------------------------------------
                                           Total:       118.3 MB

The following NEW packages will be INSTALLED:

  dbus               anaconda/osx-64::dbus-1.13.18-h18a8e69_0
  expat              anaconda/osx-64::expat-2.4.4-he9d5cce_0
  gettext            anaconda/osx-64::gettext-0.21.0-h7535e17_0
  glib               anaconda/osx-64::glib-2.69.1-h8346a28_1
  icu                anaconda/osx-64::icu-58.2-h0a44026_3
  jpeg               anaconda/osx-64::jpeg-9e-hca72f7f_0
  libiconv           anaconda/osx-64::libiconv-1.16-hca72f7f_2
  libpng             anaconda/osx-64::libpng-1.6.37-ha441bb4_0
  libxml2            anaconda/osx-64::libxml2-2.9.14-hbf8cd5e_0
  llvm-openmp        anaconda/osx-64::llvm-openmp-12.0.0-h0dcd299_1
  pcre               anaconda/osx-64::pcre-8.45-h23ab428_0
  pyqt               anaconda/osx-64::pyqt-5.9.2-py38h655552a_2
  qt                 anaconda/osx-64::qt-5.9.7-h468cd18_1
  sip                anaconda/osx-64::sip-4.19.8-py38h0a44026_0

The following packages will be SUPERSEDED by a higher-priority channel:

  ca-certificates                                 pkgs/main --> anaconda
  certifi                                         pkgs/main --> anaconda
  openssl              pkgs/main::openssl-1.1.1q-hca72f7f_0 --> anaconda::openssl-1.1.1o-hca72f7f_0


Proceed ([y]/n)? y


Downloading and Extracting Packages
ca-certificates-2022 | 132 KB    | ##################################### | 100% 
dbus-1.13.18         | 550 KB    | ##################################### | 100% 
jpeg-9e              | 266 KB    | ##################################### | 100% 
certifi-2022.6.15    | 157 KB    | ##################################### | 100% 
gettext-0.21.0       | 3.4 MB    | ##################################### | 100% 
pyqt-5.9.2           | 4.4 MB    | ##################################### | 100% 
sip-4.19.8           | 253 KB    | ##################################### | 100% 
openssl-1.1.1o       | 3.5 MB    | ##################################### | 100% 
libiconv-1.16        | 1.3 MB    | ##################################### | 100% 
icu-58.2             | 22.6 MB   | ##################################### | 100% 
libpng-1.6.37        | 325 KB    | ##################################### | 100% 
llvm-openmp-12.0.0   | 300 KB    | ##################################### | 100% 
libxml2-2.9.14       | 686 KB    | ##################################### | 100% 
expat-2.4.4          | 145 KB    | ##################################### | 100% 
glib-2.69.1          | 3.3 MB    | ##################################### | 100% 
qt-5.9.7             | 76.8 MB   | ##################################### | 100% 
pcre-8.45            | 221 KB    | ##################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done


(picasso_sr) wyssuser@wyss12422 ~ % pip install picassosr
Collecting picassosr
  Downloading picassosr-0.4.6-py3-none-any.whl (551 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 551.7/551.7 kB 6.1 MB/s eta 0:00:00
Collecting psutil==5.8.0
  Downloading psutil-5.8.0-cp38-cp38-macosx_10_9_x86_64.whl (236 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 236.3/236.3 kB 5.5 MB/s eta 0:00:00
Collecting scikit-learn==0.23.2
  Using cached scikit_learn-0.23.2-cp38-cp38-macosx_10_9_x86_64.whl (7.2 MB)
Collecting numpy>=1.19.2
  Downloading numpy-1.23.1-cp38-cp38-macosx_10_9_x86_64.whl (18.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.1/18.1 MB 8.1 MB/s eta 0:00:00
Collecting h5py>=2.10.0
  Downloading h5py-3.7.0-cp38-cp38-macosx_10_9_x86_64.whl (3.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 7.7 MB/s eta 0:00:00
Collecting matplotlib==3.3.2
  Using cached matplotlib-3.3.2-cp38-cp38-macosx_10_9_x86_64.whl (8.5 MB)
Collecting PyQt5
  Downloading PyQt5-5.15.7-cp37-abi3-macosx_10_13_x86_64.whl (7.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.0/7.0 MB 9.0 MB/s eta 0:00:00
Collecting scipy>=1.5.3
  Downloading scipy-1.8.1-cp38-cp38-macosx_12_0_universal2.macosx_10_9_x86_64.whl (55.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.3/55.3 MB 6.7 MB/s eta 0:00:00
Collecting sqlalchemy==1.4.22
  Downloading SQLAlchemy-1.4.22-cp38-cp38-macosx_10_14_x86_64.whl (1.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 5.8 MB/s eta 0:00:00
Collecting colorama==0.4.4
  Using cached colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting protobuf==3.20
  Downloading protobuf-3.20.0-cp38-cp38-macosx_10_9_x86_64.whl (962 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 962.3/962.3 kB 6.3 MB/s eta 0:00:00
Collecting watchdog==2.1.4
  Downloading watchdog-2.1.4-cp38-cp38-macosx_10_9_x86_64.whl (84 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.6/84.6 kB 2.2 MB/s eta 0:00:00
Collecting numba>=0.51.2
  Downloading numba-0.55.2-cp38-cp38-macosx_10_14_x86_64.whl (2.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 5.6 MB/s eta 0:00:00
Collecting plotly-express==0.4.1
  Downloading plotly_express-0.4.1-py2.py3-none-any.whl (2.9 kB)
Collecting streamlit==1.10.0
  Downloading streamlit-1.10.0-py2.py3-none-any.whl (9.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 6.6 MB/s eta 0:00:00
Collecting lmfit==1.0.1
  Using cached lmfit-1.0.1-py3-none-any.whl
Collecting pyyaml==5.3.1
  Using cached PyYAML-5.3.1-cp38-cp38-macosx_10_9_x86_64.whl
Collecting tqdm==4.50.2
  Using cached tqdm-4.50.2-py2.py3-none-any.whl (70 kB)
Collecting asteval>=0.9.16
  Using cached asteval-0.9.27-py3-none-any.whl (17 kB)
Collecting uncertainties>=3.0.1
  Using cached uncertainties-3.1.7-py2.py3-none-any.whl (98 kB)
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3
  Downloading pyparsing-3.0.9-py3-none-any.whl (98 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.3/98.3 kB 2.7 MB/s eta 0:00:00
Collecting cycler>=0.10
  Using cached cycler-0.11.0-py3-none-any.whl (6.4 kB)
Requirement already satisfied: certifi>=2020.06.20 in ./opt/anaconda3/envs/picasso_sr/lib/python3.8/site-packages (from matplotlib==3.3.2->picassosr) (2022.6.15)
Collecting kiwisolver>=1.0.1
  Downloading kiwisolver-1.4.4-cp38-cp38-macosx_10_9_x86_64.whl (65 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.4/65.4 kB 2.0 MB/s eta 0:00:00
Collecting pillow>=6.2.0
  Downloading Pillow-9.2.0-cp38-cp38-macosx_10_10_x86_64.whl (3.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 6.0 MB/s eta 0:00:00
Collecting python-dateutil>=2.1
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting plotly>=4.1.0
  Downloading plotly-5.9.0-py2.py3-none-any.whl (15.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.2/15.2 MB 7.6 MB/s eta 0:00:00
Collecting statsmodels>=0.9.0
  Downloading statsmodels-0.13.2-cp38-cp38-macosx_10_9_x86_64.whl (9.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.6/9.6 MB 7.9 MB/s eta 0:00:00
Collecting patsy>=0.5
  Downloading patsy-0.5.2-py2.py3-none-any.whl (233 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 233.7/233.7 kB 4.8 MB/s eta 0:00:00
Collecting pandas>=0.20.0
  Downloading pandas-1.4.3-cp38-cp38-macosx_10_9_x86_64.whl (11.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.4/11.4 MB 7.4 MB/s eta 0:00:00
Collecting joblib>=0.11
  Using cached joblib-1.1.0-py2.py3-none-any.whl (306 kB)
Collecting threadpoolctl>=2.0.0
  Downloading threadpoolctl-3.1.0-py3-none-any.whl (14 kB)
Collecting greenlet!=0.4.17
  Downloading greenlet-1.1.2-cp38-cp38-macosx_10_14_x86_64.whl (92 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.8/92.8 kB 2.9 MB/s eta 0:00:00
Collecting attrs
  Downloading attrs-21.4.0-py2.py3-none-any.whl (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 1.9 MB/s eta 0:00:00
Collecting blinker
  Downloading blinker-1.5-py2.py3-none-any.whl (12 kB)
Collecting importlib-metadata>=1.4
  Downloading importlib_metadata-4.12.0-py3-none-any.whl (21 kB)
Collecting click>=7.0
  Downloading click-8.1.3-py3-none-any.whl (96 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.6/96.6 kB 2.5 MB/s eta 0:00:00
Collecting typing-extensions
  Downloading typing_extensions-4.3.0-py3-none-any.whl (25 kB)
Collecting cachetools>=4.0
  Downloading cachetools-5.2.0-py3-none-any.whl (9.3 kB)
Collecting tzlocal
  Downloading tzlocal-4.2-py3-none-any.whl (19 kB)
Collecting pydeck>=0.1.dev5
  Downloading pydeck-0.7.1-py2.py3-none-any.whl (4.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 7.2 MB/s eta 0:00:00
Collecting pyarrow
  Downloading pyarrow-8.0.0-cp38-cp38-macosx_10_13_x86_64.whl (22.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 22.4/22.4 MB 8.5 MB/s eta 0:00:00
Collecting gitpython!=3.1.19
  Downloading GitPython-3.1.27-py3-none-any.whl (181 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 181.2/181.2 kB 5.2 MB/s eta 0:00:00
Collecting requests
  Downloading requests-2.28.1-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 kB 2.0 MB/s eta 0:00:00
Collecting validators
  Downloading validators-0.20.0.tar.gz (30 kB)
  Preparing metadata (setup.py) ... done
Collecting toml
  Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting rich
  Downloading rich-12.5.1-py3-none-any.whl (235 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 235.6/235.6 kB 4.8 MB/s eta 0:00:00
Collecting tornado>=5.0
  Downloading tornado-6.2-cp37-abi3-macosx_10_9_x86_64.whl (419 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 419.7/419.7 kB 6.3 MB/s eta 0:00:00
Collecting packaging
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
Collecting pympler>=0.9
  Downloading Pympler-1.0.1-py3-none-any.whl (164 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 164.8/164.8 kB 4.7 MB/s eta 0:00:00
Collecting altair>=3.2.0
  Downloading altair-4.2.0-py3-none-any.whl (812 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 812.8/812.8 kB 6.8 MB/s eta 0:00:00
Collecting semver
  Downloading semver-2.13.0-py2.py3-none-any.whl (12 kB)
Collecting llvmlite<0.39,>=0.38.0rc1
  Downloading llvmlite-0.38.1-cp38-cp38-macosx_10_9_x86_64.whl (25.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.5/25.5 MB 7.1 MB/s eta 0:00:00
Requirement already satisfied: setuptools in ./opt/anaconda3/envs/picasso_sr/lib/python3.8/site-packages (from numba>=0.51.2->picassosr) (61.2.0)
Collecting numpy>=1.19.2
  Downloading numpy-1.22.4-cp38-cp38-macosx_10_15_x86_64.whl (17.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.6/17.6 MB 8.3 MB/s eta 0:00:00
Collecting PyQt5-sip<13,>=12.11
  Downloading PyQt5_sip-12.11.0-cp38-cp38-macosx_10_9_x86_64.whl (84 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.8/84.8 kB 3.4 MB/s eta 0:00:00
Collecting PyQt5-Qt5>=5.15.0
  Using cached PyQt5_Qt5-5.15.2-py3-none-macosx_10_13_intel.whl (40.5 MB)
Collecting jsonschema>=3.0
  Downloading jsonschema-4.7.2-py3-none-any.whl (81 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.1/81.1 kB 2.4 MB/s eta 0:00:00
Collecting toolz
  Downloading toolz-0.12.0-py3-none-any.whl (55 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.8/55.8 kB 2.1 MB/s eta 0:00:00
Collecting jinja2
  Downloading Jinja2-3.1.2-py3-none-any.whl (133 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.1/133.1 kB 3.0 MB/s eta 0:00:00
Collecting entrypoints
  Downloading entrypoints-0.4-py3-none-any.whl (5.3 kB)
Collecting gitdb<5,>=4.0.1
  Downloading gitdb-4.0.9-py3-none-any.whl (63 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.1/63.1 kB 2.2 MB/s eta 0:00:00
Collecting zipp>=0.5
  Downloading zipp-3.8.1-py3-none-any.whl (5.6 kB)
Collecting pytz>=2020.1
  Downloading pytz-2022.1-py2.py3-none-any.whl (503 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 503.5/503.5 kB 7.1 MB/s eta 0:00:00
Collecting six
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting tenacity>=6.2.0
  Downloading tenacity-8.0.1-py3-none-any.whl (24 kB)
Collecting ipykernel>=5.1.2
  Downloading ipykernel-6.15.1-py3-none-any.whl (132 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.9/132.9 kB 4.4 MB/s eta 0:00:00
Collecting ipywidgets>=7.0.0
  Downloading ipywidgets-7.7.1-py2.py3-none-any.whl (123 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 123.4/123.4 kB 3.9 MB/s eta 0:00:00
Collecting traitlets>=4.3.2
  Downloading traitlets-5.3.0-py3-none-any.whl (106 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 106.8/106.8 kB 3.2 MB/s eta 0:00:00
Collecting future
  Using cached future-0.18.2-py3-none-any.whl
Collecting idna<4,>=2.5
  Downloading idna-3.3-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.2/61.2 kB 2.5 MB/s eta 0:00:00
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.10-py2.py3-none-any.whl (139 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.2/139.2 kB 4.3 MB/s eta 0:00:00
Collecting charset-normalizer<3,>=2
  Downloading charset_normalizer-2.1.0-py3-none-any.whl (39 kB)
Collecting pygments<3.0.0,>=2.6.0
  Downloading Pygments-2.12.0-py3-none-any.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 6.0 MB/s eta 0:00:00
Collecting commonmark<0.10.0,>=0.9.0
  Downloading commonmark-0.9.1-py2.py3-none-any.whl (51 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.1/51.1 kB 2.0 MB/s eta 0:00:00
Collecting pytz-deprecation-shim
  Downloading pytz_deprecation_shim-0.1.0.post0-py2.py3-none-any.whl (15 kB)
Collecting backports.zoneinfo
  Downloading backports.zoneinfo-0.2.1-cp38-cp38-macosx_10_14_x86_64.whl (35 kB)
Collecting decorator>=3.4.0
  Downloading decorator-5.1.1-py3-none-any.whl (9.1 kB)
Collecting smmap<6,>=3.0.1
  Downloading smmap-5.0.0-py3-none-any.whl (24 kB)
Collecting matplotlib-inline>=0.1
  Downloading matplotlib_inline-0.1.3-py3-none-any.whl (8.2 kB)
Collecting jupyter-client>=6.1.12
  Downloading jupyter_client-7.3.4-py3-none-any.whl (132 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.1/132.1 kB 3.8 MB/s eta 0:00:00
Collecting ipython>=7.23.1
  Downloading ipython-8.4.0-py3-none-any.whl (750 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 750.8/750.8 kB 7.5 MB/s eta 0:00:00
Collecting nest-asyncio
  Downloading nest_asyncio-1.5.5-py3-none-any.whl (5.2 kB)
Collecting pyzmq>=17
  Downloading pyzmq-23.2.0-cp38-cp38-macosx_10_9_x86_64.whl (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 6.4 MB/s eta 0:00:00
Collecting appnope
  Downloading appnope-0.1.3-py2.py3-none-any.whl (4.4 kB)
Collecting debugpy>=1.0
  Downloading debugpy-1.6.2-cp38-cp38-macosx_10_15_x86_64.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 6.5 MB/s eta 0:00:00
Collecting ipython-genutils~=0.2.0
  Downloading ipython_genutils-0.2.0-py2.py3-none-any.whl (26 kB)
Collecting widgetsnbextension~=3.6.0
  Downloading widgetsnbextension-3.6.1-py2.py3-none-any.whl (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 7.2 MB/s eta 0:00:00
Collecting jupyterlab-widgets>=1.0.0
  Downloading jupyterlab_widgets-1.1.1-py3-none-any.whl (245 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 245.3/245.3 kB 5.1 MB/s eta 0:00:00
Collecting MarkupSafe>=2.0
  Downloading MarkupSafe-2.1.1-cp38-cp38-macosx_10_9_x86_64.whl (13 kB)
Collecting pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0
  Downloading pyrsistent-0.18.1-cp38-cp38-macosx_10_9_universal2.whl (81 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.4/81.4 kB 1.2 MB/s eta 0:00:00
Collecting importlib-resources>=1.4.0
  Downloading importlib_resources-5.8.0-py3-none-any.whl (28 kB)
Collecting tzdata
  Downloading tzdata-2022.1-py2.py3-none-any.whl (339 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 339.5/339.5 kB 6.9 MB/s eta 0:00:00
Collecting pexpect>4.3
  Downloading pexpect-4.8.0-py2.py3-none-any.whl (59 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.0/59.0 kB 2.3 MB/s eta 0:00:00
Collecting stack-data
  Downloading stack_data-0.3.0-py3-none-any.whl (23 kB)
Collecting prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0
  Downloading prompt_toolkit-3.0.30-py3-none-any.whl (381 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 381.7/381.7 kB 6.9 MB/s eta 0:00:00
Collecting backcall
  Downloading backcall-0.2.0-py2.py3-none-any.whl (11 kB)
Collecting jedi>=0.16
  Downloading jedi-0.18.1-py2.py3-none-any.whl (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 9.3 MB/s eta 0:00:00
Collecting pickleshare
  Downloading pickleshare-0.7.5-py2.py3-none-any.whl (6.9 kB)
Collecting jupyter-core>=4.9.2
  Downloading jupyter_core-4.11.1-py3-none-any.whl (88 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.4/88.4 kB 2.7 MB/s eta 0:00:00
Collecting notebook>=4.4.1
  Downloading notebook-6.4.12-py3-none-any.whl (9.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 9.3 MB/s eta 0:00:00
Collecting parso<0.9.0,>=0.8.0
  Downloading parso-0.8.3-py2.py3-none-any.whl (100 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.8/100.8 kB 3.2 MB/s eta 0:00:00
Collecting nbformat
  Downloading nbformat-5.4.0-py3-none-any.whl (73 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.3/73.3 kB 2.3 MB/s eta 0:00:00
Collecting nbconvert>=5
  Downloading nbconvert-6.5.0-py3-none-any.whl (561 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 561.6/561.6 kB 6.1 MB/s eta 0:00:00
Collecting prometheus-client
  Downloading prometheus_client-0.14.1-py3-none-any.whl (59 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.5/59.5 kB 2.2 MB/s eta 0:00:00
Collecting Send2Trash>=1.8.0
  Downloading Send2Trash-1.8.0-py3-none-any.whl (18 kB)
Collecting argon2-cffi
  Downloading argon2_cffi-21.3.0-py3-none-any.whl (14 kB)
Collecting terminado>=0.8.3
  Downloading terminado-0.15.0-py3-none-any.whl (16 kB)
Collecting ptyprocess>=0.5
  Downloading ptyprocess-0.7.0-py2.py3-none-any.whl (13 kB)
Collecting wcwidth
  Downloading wcwidth-0.2.5-py2.py3-none-any.whl (30 kB)
Collecting executing
  Downloading executing-0.8.3-py2.py3-none-any.whl (16 kB)
Collecting asttokens
  Downloading asttokens-2.0.5-py2.py3-none-any.whl (20 kB)
Collecting pure-eval
  Downloading pure_eval-0.2.2-py3-none-any.whl (11 kB)
Collecting pandocfilters>=1.4.1
  Downloading pandocfilters-1.5.0-py2.py3-none-any.whl (8.7 kB)
Collecting defusedxml
  Downloading defusedxml-0.7.1-py2.py3-none-any.whl (25 kB)
Collecting nbclient>=0.5.0
  Downloading nbclient-0.6.6-py3-none-any.whl (71 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.8/71.8 kB 2.4 MB/s eta 0:00:00
Collecting tinycss2
  Downloading tinycss2-1.1.1-py3-none-any.whl (21 kB)
Collecting mistune<2,>=0.8.1
  Downloading mistune-0.8.4-py2.py3-none-any.whl (16 kB)
Collecting jupyterlab-pygments
  Downloading jupyterlab_pygments-0.2.2-py2.py3-none-any.whl (21 kB)
Collecting beautifulsoup4
  Downloading beautifulsoup4-4.11.1-py3-none-any.whl (128 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 128.2/128.2 kB 3.9 MB/s eta 0:00:00
Collecting bleach
  Downloading bleach-5.0.1-py3-none-any.whl (160 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 160.9/160.9 kB 4.1 MB/s eta 0:00:00
Collecting fastjsonschema
  Downloading fastjsonschema-2.16.1-py3-none-any.whl (22 kB)
Collecting argon2-cffi-bindings
  Downloading argon2_cffi_bindings-21.2.0-cp38-abi3-macosx_10_9_universal2.whl (53 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.1/53.1 kB 1.8 MB/s eta 0:00:00
Collecting cffi>=1.0.1
  Downloading cffi-1.15.1-cp38-cp38-macosx_10_9_x86_64.whl (178 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 178.9/178.9 kB 3.7 MB/s eta 0:00:00
Collecting soupsieve>1.2
  Downloading soupsieve-2.3.2.post1-py3-none-any.whl (37 kB)
Collecting webencodings
  Downloading webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Collecting pycparser
  Downloading pycparser-2.21-py2.py3-none-any.whl (118 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.7/118.7 kB 3.6 MB/s eta 0:00:00
Building wheels for collected packages: validators
  Building wheel for validators (setup.py) ... done
  Created wheel for validators: filename=validators-0.20.0-py3-none-any.whl size=19582 sha256=fc43eb5d36343489997de6fc86d8704d96744034d3d59c54940c337c73eba633
  Stored in directory: /Users/wyssuser/Library/Caches/pip/wheels/19/09/72/3eb74d236bb48bd0f3c6c3c83e4e0c5bbfcbcad7c6c3539db8
Successfully built validators
Installing collected packages: webencodings, wcwidth, Send2Trash, pytz, PyQt5-Qt5, pure-eval, ptyprocess, pickleshare, mistune, ipython-genutils, fastjsonschema, executing, commonmark, backcall, appnope, zipp, watchdog, urllib3, tzdata, typing-extensions, traitlets, tqdm, tornado, toolz, toml, tinycss2, threadpoolctl, tenacity, soupsieve, smmap, six, semver, pyzmq, pyyaml, pyrsistent, PyQt5-sip, pyparsing, pympler, pygments, pycparser, psutil, protobuf, prompt-toolkit, prometheus-client, pillow, pexpect, parso, pandocfilters, numpy, nest-asyncio, MarkupSafe, llvmlite, kiwisolver, jupyterlab-widgets, jupyterlab-pygments, joblib, idna, greenlet, future, entrypoints, defusedxml, decorator, debugpy, cycler, colorama, click, charset-normalizer, cachetools, blinker, backports.zoneinfo, attrs, asteval, validators, uncertainties, terminado, sqlalchemy, scipy, rich, requests, pytz-deprecation-shim, python-dateutil, PyQt5, pyarrow, plotly, patsy, packaging, numba, matplotlib-inline, jupyter-core, jinja2, jedi, importlib-resources, importlib-metadata, h5py, gitdb, cffi, bleach, beautifulsoup4, asttokens, tzlocal, stack-data, scikit-learn, pandas, matplotlib, lmfit, jupyter-client, jsonschema, gitpython, argon2-cffi-bindings, statsmodels, nbformat, ipython, argon2-cffi, altair, plotly-express, nbclient, ipykernel, nbconvert, notebook, widgetsnbextension, ipywidgets, pydeck, streamlit, picassosr
Successfully installed MarkupSafe-2.1.1 PyQt5-5.15.7 PyQt5-Qt5-5.15.2 PyQt5-sip-12.11.0 Send2Trash-1.8.0 altair-4.2.0 appnope-0.1.3 argon2-cffi-21.3.0 argon2-cffi-bindings-21.2.0 asteval-0.9.27 asttokens-2.0.5 attrs-21.4.0 backcall-0.2.0 backports.zoneinfo-0.2.1 beautifulsoup4-4.11.1 bleach-5.0.1 blinker-1.5 cachetools-5.2.0 cffi-1.15.1 charset-normalizer-2.1.0 click-8.1.3 colorama-0.4.4 commonmark-0.9.1 cycler-0.11.0 debugpy-1.6.2 decorator-5.1.1 defusedxml-0.7.1 entrypoints-0.4 executing-0.8.3 fastjsonschema-2.16.1 future-0.18.2 gitdb-4.0.9 gitpython-3.1.27 greenlet-1.1.2 h5py-3.7.0 idna-3.3 importlib-metadata-4.12.0 importlib-resources-5.8.0 ipykernel-6.15.1 ipython-8.4.0 ipython-genutils-0.2.0 ipywidgets-7.7.1 jedi-0.18.1 jinja2-3.1.2 joblib-1.1.0 jsonschema-4.7.2 jupyter-client-7.3.4 jupyter-core-4.11.1 jupyterlab-pygments-0.2.2 jupyterlab-widgets-1.1.1 kiwisolver-1.4.4 llvmlite-0.38.1 lmfit-1.0.1 matplotlib-3.3.2 matplotlib-inline-0.1.3 mistune-0.8.4 nbclient-0.6.6 nbconvert-6.5.0 nbformat-5.4.0 nest-asyncio-1.5.5 notebook-6.4.12 numba-0.55.2 numpy-1.22.4 packaging-21.3 pandas-1.4.3 pandocfilters-1.5.0 parso-0.8.3 patsy-0.5.2 pexpect-4.8.0 picassosr-0.4.6 pickleshare-0.7.5 pillow-9.2.0 plotly-5.9.0 plotly-express-0.4.1 prometheus-client-0.14.1 prompt-toolkit-3.0.30 protobuf-3.20.0 psutil-5.8.0 ptyprocess-0.7.0 pure-eval-0.2.2 pyarrow-8.0.0 pycparser-2.21 pydeck-0.7.1 pygments-2.12.0 pympler-1.0.1 pyparsing-3.0.9 pyrsistent-0.18.1 python-dateutil-2.8.2 pytz-2022.1 pytz-deprecation-shim-0.1.0.post0 pyyaml-5.3.1 pyzmq-23.2.0 requests-2.28.1 rich-12.5.1 scikit-learn-0.23.2 scipy-1.8.1 semver-2.13.0 six-1.16.0 smmap-5.0.0 soupsieve-2.3.2.post1 sqlalchemy-1.4.22 stack-data-0.3.0 statsmodels-0.13.2 streamlit-1.10.0 tenacity-8.0.1 terminado-0.15.0 threadpoolctl-3.1.0 tinycss2-1.1.1 toml-0.10.2 toolz-0.12.0 tornado-6.2 tqdm-4.50.2 traitlets-5.3.0 typing-extensions-4.3.0 tzdata-2022.1 tzlocal-4.2 uncertainties-3.1.7 urllib3-1.26.10 validators-0.20.0 watchdog-2.1.4 wcwidth-0.2.5 webencodings-0.5.1 widgetsnbextension-3.6.1 zipp-3.8.1

(picasso_sr) wyssuser@wyss12422 ~ % picasso localize
Traceback (most recent call last):
  File "/Users/wyssuser/opt/anaconda3/envs/picasso_sr/bin/picasso", line 8, in <module>
    sys.exit(main())
  File "/Users/wyssuser/opt/anaconda3/envs/picasso_sr/lib/python3.8/site-packages/picasso/__main__.py", line 1530, in main
    from picasso.gui import localize
  File "/Users/wyssuser/opt/anaconda3/envs/picasso_sr/lib/python3.8/site-packages/picasso/gui/localize.py", line 19, in <module>
    from .. import io, localize, gausslq, gaussmle, zfit, lib, CONFIG, avgroi
  File "/Users/wyssuser/opt/anaconda3/envs/picasso_sr/lib/python3.8/site-packages/picasso/io.py", line 23, in <module>
    from .ext.bitplane import IMSWRITER
ModuleNotFoundError: No module named 'picasso.ext'
```

**Comment by straussmaximilian** [comment]
Could you check if the error also occurs when you start picasso with `python -m picasso localize`?
In any case, I just pushed a new version to PyPi that should fix the underlying import error. Please comment in case this works/does not.

**Comment by steinjohannes** [comment]
Hi Max, 

thanks for your quick response. I still received the same error regardless of wether using '''python -m picasso localize''' or '''picasso localize'''. I checked the picasso package content '''/Users/wyssuser/opt/anaconda3/envs/picasso_sr/lib/python3.8/site-packages/picasso''' and found that indeed the folder 'ext' containing bitplane.py was missing. Copying it in from the current repo fixed the issue. I also checked at [https://pypi.org/project/picassosr/](https://pypi.org/project/picassosr/), it's also missing here. I guess running the builder once more should fix that?

**Comment by straussmaximilian** [comment]
Hi,
I did publish an updated version to PyPi again. Could you try if it works (`pip install picassor --upgrade`) now?

**Comment by steinjohannes** [comment]
Works, thanks Max!
