### ISSUE TITLE
Batch processing with command line

### ISSUE THREAD

**Issue by kfriedl** [jungmannlab/picasso#39]
Hi, I am trying to set up a batch file to process data via command line. Unfortunately our data (*.raw) is not recognized by the module localize. Maybe glob is causing the error, a small test on the same directory with os.listdir() and fnmatch worked well.

**Comment by straussmaximilian** [comment]
Hi,
when using raw files, you need to have a corresponding *.yaml file so that the image dimensions are known. 
I just pushed a commit that checks if each *.raw file has a *.yaml file. If not, the program asks for the image specifications. Here you can enter the details and choose to either be prompted again for all the other *.raw files or use the same specs for all remaining files.
Do you mind testing this out?
Also, let me know if you had a different workflow in mind.

**Comment by kfriedl** [comment]
I converted the files to raw with your raw/yaml plugin, so the files are all there. I tested the change, but still get a FileNotFoundError,

**Comment by straussmaximilian** [comment]
Hi, could you paste the error message? Which OS are you using?

**Comment by kfriedl** [comment]
Windows 10
![snap_error_message](https://user-images.githubusercontent.com/27196897/52960875-fc743d80-3399-11e9-9020-872fe29f302d.png)

**Comment by hiroshisasak1** [comment]
Hi all,
I think it is because, in check_consecutive_tif(filepath) in __main__.py, only .tif files are searched while running Picasso Localize via CUI.

Line 643 in __main__.py
>         files = glob(filepath + "/*.tif")

I use the code changing .tif to .raw by myself.

**Comment by kfriedl** [comment]
I see! In line 669 it's glob(filepath+"*.raw"), maybe the slash is missing

**Comment by straussmaximilian** [comment]
Hi,
The check_consecutive is unrelated; this is only meant to find consecutive TIFs and treat them as one. This is intentionally TIF only. A couple lines later you can find  `paths = tif_files + glob(files + "*.raw")` to include the *.raw files as kfriedl noted.

It seems that you have the installer version plus the GitHub version running. I tested both and noticed that the batch mode gets an error when calling the installer version (see Screenshots) and works fine when calling the GitHub version.

Therefore I would recommend calling "python -m picasso localize ..." to call the GitHub version. I'll investigate what's wrong with the installer. 

![screen shot 2019-02-18 at 4 36 41 pm](https://user-images.githubusercontent.com/16521288/52961812-131b9400-339c-11e9-8a11-856a8891cf01.png)
![screen shot 2019-02-18 at 4 33 38 pm](https://user-images.githubusercontent.com/16521288/52961813-131b9400-339c-11e9-9dd4-5600806110f4.png)

**Comment by kfriedl** [comment]
So I had a try and changed line 669 to glob(files+"/.raw") and the slash does the trick. Sorry to have caused so much trouble for this minor problem!

**Comment by straussmaximilian** [comment]
Hi, no trouble here - glad if things worked out. I changed it accordingly and will compile a new installer (v0.2.7).
